name: ci-run

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build run Docker images
      working-directory: base
      run: ./build-all-run.sh
    - name: List Docker images
      run: |
        docker images
